source 'https://rubygems.org'

gem 'foreman'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'dotenv'
gem 'httparty'
gem 'awesome_print'
gem 'json'
gem 'nest_thermostat', :github => 'christianmadden/nest_thermostat'
gem 'oauth2'
gem 'hue', :github => 'soffes/hue'
gem 'persist'
