source 'https://rubygems.org'

gem 'foreman'
gem 'sinatra'
gem 'thin'
gem 'dotenv'
gem 'awesome_print'
gem 'json'
gem 'nest_thermostat', :github => 'christianmadden/nest_thermostat'
gem 'omniauth'
gem 'omniauth-automatic'
gem 'automatic-client'
gem 'hue'
